### ISSUE TITLE
bug: additional auth cases

### ISSUE THREAD

**Issue by sebastus** [aztfmod/rovergo#106]
Additional authentication cases have been discovered. We need all of them to be handled correctly.

## Expected Behavior

All of these authentication cases should work, az login: (on an Azure VM)
- with only a system assigned MI
- with a system assigned MI and a user assigned MI
- with only a user assigned MI
- with >1 user assigned MI
- with a system assigned MI and >1 user assigned MI
- with an app registration (spn) (client-id + client secret)

All of the above cases should work where the logged in ID has permissions:
- owner on subscription
- owner on something else, but not the subscription
- owner on nothing at all

In cases above where --username (-u) parameter is specified to az login, must work with: (with MI only - not spn)
- client-id
- object-id
- resource-id

In addition to the above cases, az login with a user principal should work:
- with and without owner perms on subscription
- with owner on something else than the subscription (fail with relevant messaging)
- with owner on nothing at all (but possibly contributor, etc) (fail with relevant messaging)

Desired outcome includes creation of unit tests for each of the cases.

## Actual Behavior

Some of the above cases are handled correctly, but not all.

**Comment by benc-uk** [comment]
A major note on the owner role check, the only time it needs to be checked is for **_launchpad_** mode only
See the old rover code

![image](https://user-images.githubusercontent.com/14982936/122412407-6eb2b800-cf7d-11eb-9ba1-6213bc805185.png)

**Comment by benc-uk** [comment]
Getting the objectId however is mandatory and is required by the CAF terraform in a TF_VAR

**Comment by sebastus** [comment]
The initial stage of resolving this issue is to enumerate the cases as comments in `test/integration/auth_test.go`
