### ISSUE TITLE
Implement: action/command grouping and chaining

### ISSUE THREAD

**Issue by benc-uk** [aztfmod/rovergo#109]
This is to implement the output design from #108 

## Reasons

- See #108

## Notes / Considerations

- None yet

## Outcomes

- [x] Create yml files for all tools in pkg/custom/source.
- [x] Create default groups.yml and add it to pkg/custom/source
- [x]  Document which variables are available for tool authors.
- [x]  Design groups.yml syntax.
- [x]  Integrate groups with command line.
- [x]  Add validation between group name and custom command name.
- [x]  Modify usage (--help) to show groups in a separate area as compared to top level build in actions.
- [x]  Order of actions in the group should be the order of execution.
- [x]  Support running init with no backend (for ci tools that need init)
- [x]  Refactor custom actions to be a single yaml file instead of multiple.
- [x] #129

**Comment by polatengin** [comment]
PR #137 does this issue, somehow, we missed it and left it open, closing it now.
