### ISSUE TITLE
CI tasks parsing

### ISSUE THREAD

**Issue by benc-uk** [aztfmod/rovergo#15]
Current CI command reads both symphony YAML and also YAML in ci_tasks directory, each of these YAMLs defines a task that can be run in CI mode

These files will need to be parsed, and will form the core of the `ci` command implementation. Once the file is passed it takes the extra params from symphony YAML (e.g. working directory, path to vars, level etc) and executes the task by dropping down to the shell

For terraform commands I think tf-exec should be used rather shell

This task is just for parsing the YAML

Building the task runner is in task xxxx

**Comment by sebastus** [comment]
resolved by #28
