### ISSUE TITLE
Implement KeyVault dataplane access

### ISSUE THREAD

**Issue by benc-uk** [aztfmod/rovergo#22]
Secrets will need to be fetched, as part of #21 

- [ ] Investigate Go options, SDK
- [ ] How we will authenticate 
- [ ] Ensure authentication works along side current Terraform and Azure API auth
- [ ] Create wrapper / helper package to get secrets specifically for rover use case

**Comment by sebastus** [comment]
re: investigate go options, SDK. There are [several](https://github.com/Azure/azure-sdk-for-go/tree/master/services/keyvault). I took the most recent.

re: how will we authenticate. We took a decision to authenticate via the az cli. This is how it's done in the sdk:
`authorizer, err := auth.NewAuthorizerFromCLIWithResource(audience)`
where `audience` is the resource url for keyvault (e.g. `https://vault.azure.net)`

re: ensure authentication works...
Well, yes. 

re: create wrapper, etc. 
`GetSecret()` supports 90% of use cases.
