### ISSUE TITLE
CI tasks execution

### ISSUE THREAD

**Issue by benc-uk** [aztfmod/rovergo#23]
- Implement task runner for the CI tasks as defined in issue #15 
- Will need to run from symphony.yaml so parser will need to be complete #14 
- Using the existing tf-exec code in terraform.go and command.go implementation should be relatively easy

**Comment by sebastus** [comment]
CI task menu options are added dynamically according to the yaml files in the ci_tasks folder. This task takes it a step further to actually run the CI task requested by the user.
