### ISSUE TITLE
Symphony YAML Syntax

### ISSUE THREAD

**Issue by hattan** [aztfmod/rovergo#39]
Opening this issue to discuss the proposed changes here:
https://github.com/aztfmod/rovergo/wiki/Symphony-v2---Draft-Proposal

**Comment by hattan** [comment]
* move landingZonePath to top level, not inside a stack
 Add a cu

Landing Zone really needs to be part of the stack itself because there might be different landing zone repos for a project and underlying stack.  

The current symphony deployment target is :

* One repo for out of  the box landing zones (caf_launchpad and caf_solution). This is generally 1-1 with what's released in the landing zone repos.

* One repo for every stack that requires custom add-ons, private modules or a specific landing zone. 
* One config repo per stack.

* Config Repo for Launchpad
* Config Repo for Platform (level1 and level2)

Each stack would be comprised of a config repo and a modules repo.

This is the reference app. This is a gitlab group (similar to github org) with project (repos) underneath.
![image](https://user-images.githubusercontent.com/268713/120798898-e0f1ba00-c4f2-11eb-9e5a-3ddd9ca7c7be.png)

**Comment by benc-uk** [comment]
@hattan Makes sense re the `landingZonePath` key, moving it to under the stack has been done
