### ISSUE TITLE
rover cd destroy doesn't work

### ISSUE THREAD

**Issue by sebastus** [aztfmod/rovergo#69]
I tried it a couple of ways:

rover cd destroy 
rover lp destroy -c $HOME/caf_config/demo/level0 -s $HOME/git/caf-terraform-landingzones -l level0

This may be due to the fact that I changed some things in caf_config. As follows:

resource_groups = {
  level0 = {
    name = "lp-l0"
    tags = {
      level = "level0"
    }
  } ... etc

**Comment by sebastus** [comment]
I deleted my launch pad manually, then re-installed with a caf_config in which I changed nothing. Immediately after `rover lp apply`, did a `rover lp destroy` and it worked normally.

**Comment by benc-uk** [comment]
We need to look into cd destroy.

it seems to be working fine for me, but without a --level it will try to destroy all levels BUT starting with the launchpad which of course will nuke all remote state causing all other destroy to fail. Probably just need to run it in reverse

**Comment by benc-uk** [comment]
Also running this `cd destroy -c samples/ref-app/symphony.yml --level level0` failed for me

with `Error: variable "landingzone" was required but not supplied` don't know why :(

**Comment by benc-uk** [comment]
I just had an error in my config. PR #72 puts checks in place which would have caught this

The deletion in reverse issue still holds
