### ISSUE TITLE
rover lp destroy command line not parsing -c correctly

### ISSUE THREAD

**Issue by sebastus** [aztfmod/rovergo#70]
When I tried this command with an incorrect -c parameter, the command tried to run anyway, gave incorrect results.

rover lp destroy -c $HOME/caf_config -s $HOME/git/caf-terraform-landingzones -l level0

I left off /demo/level0 from the -c parameter.

**Comment by benc-uk** [comment]
The implementation is naïve and doesn't check for the existence of the folder PLUS doesn't check if the folder contains any .tfvar files, those check would probably fix this.

Of course there's no way to stop a user pointing it a folder filled with totally incorrect .tfvars
