### ISSUE TITLE
testdata: refactor

### ISSUE THREAD

**Issue by sebastus** [aztfmod/rovergo#99]
Relocate pkg/testdata to /test/testdata
Relocate existing pkg/*_test.go to /test
Rename /samples to /examples
Ensure configurations still work, (level0 & level1) whether from command line or debugging using launch.json in vs code.

## Reasons

- don't want testdata in the end user's environment
- desire to conform to [standard project layout](https://github.com/golang-standards/project-layout)

## Notes / Considerations

- using existing samples runs the risk that samples get changed without consideration of tests
- new tests will most likely need additional data - do we want that in samples?
- fundamental difference between 'samples' and 'testdata'

## Outcomes

- pkg/testdata is moved to /test/testdata
- existing unit tests work with test data in new location and are located in /test somewhere
- existing launch.json configuration works with new test data location so future devs can just get to work rather than debugging dev configuration

**Comment by benc-uk** [comment]
I definitely think pkg/ should remain unpolluted of things like test data

If we're following the golang project structure https://github.com/golang-standards/project-layout and we loosely have been until now.

Then it should reside in a folder called test/ in root of the repo
And if we follow that then samples/ should be renamed examples/

**Comment by sebastus** [comment]
Thanks for the reference. I'll include in the PR for this issue movement of existing test to conform to that standard. (amended above)

**Comment by sebastus** [comment]
resolved by #111
